# Generated by Django 3.2.13 on 2022-07-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='rate',
            new_name='goal_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
