# Generated by Django 3.2.13 on 2022-07-24 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20220723_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Workout',
        ),
    ]
