# Generated by Django 3.2.13 on 2022-06-27 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traininglog', '0007_alter_log1_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log1',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Log2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=50)),
                ('time2', models.CharField(max_length=50)),
                ('time3', models.CharField(max_length=50)),
                ('time4', models.CharField(max_length=50)),
                ('time5', models.CharField(max_length=50)),
                ('time6', models.CharField(max_length=50)),
                ('time7', models.CharField(max_length=50)),
                ('time8', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
