# Generated by Django 3.2.13 on 2022-07-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglog', '0020_auto_20220724_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='goal',
            field=models.TimeField(null=True),
        ),
    ]
