# Generated by Django 3.2.13 on 2022-07-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traininglog', '0023_rename_workout_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal',
            new_name='goal_time',
        ),
    ]
