# Generated by Django 3.2.13 on 2022-07-26 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('traininglog', '0027_auto_20220726_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_time',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_daily',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
