# Generated by Django 3.2.13 on 2022-07-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglog', '0029_auto_20220726_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_date',
            field=models.DateField(null=True),
        ),
    ]
