# Generated by Django 3.2.13 on 2022-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglog', '0003_auto_20220726_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_daily',
            field=models.CharField(default='Do 6x400m intervals at 90s/400m', max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_description',
            field=models.CharField(default='Run 2.4km in 9 minutes', max_length=50),
        ),
    ]
