# Generated by Django 3.2.13 on 2022-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglog', '0019_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='pace',
            field=models.IntegerField(default=124),
        ),
        migrations.AlterField(
            model_name='workout',
            name='goal',
            field=models.IntegerField(default=124),
        ),
        migrations.AlterField(
            model_name='workout',
            name='goal_date',
            field=models.DateField(null=True),
        ),
    ]
