# Generated by Django 3.2.13 on 2022-07-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglog', '0021_alter_workout_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='pace',
        ),
        migrations.AlterField(
            model_name='workout',
            name='goal',
            field=models.CharField(choices=[('8', '8 mins'), ('9', '9 mins'), ('10', '10 mins'), ('11', '11 mins'), ('12', '12 mins'), ('13', '13 mins'), ('14', '14 mins'), ('15', '15 mins'), ('16', '16 mins')], default='12', max_length=20),
        ),
    ]
