# Generated by Django 3.2.13 on 2022-07-25 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traininglog', '0022_auto_20220725_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='Goal',
        ),
    ]
