# Generated by Django 3.2.13 on 2022-07-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglog', '0025_alter_goal_goal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_time',
            field=models.IntegerField(default=12),
        ),
    ]
