# Generated by Django 3.2.13 on 2022-07-26 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traininglog', '0028_auto_20220726_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_daily',
            field=models.CharField(default='run for 20 minutes', max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_description',
            field=models.CharField(default='Keep healthy', max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to=settings.AUTH_USER_MODEL),
        ),
    ]
